name: Keep Render Alive

on:
  schedule:
    - cron: "*/1 * * * *"  # Ejecuta cada minuto

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render service
        run: curl -s -o /dev/null -w "%{http_code}" https://votacion.onrender.com
